import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-green-500 text-center text-2xl">
        <h1 className='text-blue-900'>Hello world</h1>
        <div className='text-red-500'>

          <p className=''>sldjfldj</p>
        </div>
      </main>
    </>
  )
}
